language: cpp

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update
 
install:
 - travis_retry sudo apt-get install haxe -y --force-yes
 - travis_retry sudo apt-get install gcc-multilib g++-multilib -y
 - mkdir ~/haxelib
 - haxelib setup ~/haxelib
 - travis_retry haxelib install hxcpp

script:
 - bash test/test.sh linux
 - bash test/test.sh neko
